version: "2"
linters:
  enable:
    - dogsled
    - dupl
    - errname
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - godox
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - mnd
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 300
    gocritic:
      enabled-checks:
        - ruleguard
      disabled-checks:
        - regexpMust
        - appendAssign
        - rangeValCopy
        - exitAfterDefer
        - elseif
        - dupBranchBody
        - assignOp
        - singleCaseSwitch
        - unlambda
        - captLocal
        - commentFormatting
        - ifElseChain
        - importShadow
        - paramTypeCombine
        - builtinShadow
        - typeUnparen
      enabled-tags:
        - performance
        - diagnostic
        - opinionated
      disabled-tags:
        - experimental
    gosec:
      excludes:
        - G115
        - G602
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
