name: Lint
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'release/**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Lint
        run: |
          make install-linter
          make lint
