---
    name: Test
    on:
      push:
        branches:
          - main
      pull_request:
    
    jobs:
      test:
        strategy:
          matrix:
            go-version: [ 1.25 ]
            goarch: [ "amd64" ]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    
        - name: Install Go
          uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
          with:
            go-version: ${{ matrix.go-version }}
          env:
            GOARCH: ${{ matrix.goarch }}
    
        - name: Test
          run: make test
          working-directory: ./


        - name: Archive code coverage results
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
          with:
            name: code-coverage-report
            path: coverage.out

      sonar-cloud:
        needs: test
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
            with:
              submodules: recursive
              fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

          - name: Download code coverage results
            uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
            with:
              name: code-coverage-report

          - name: SonarCloud analysis
            uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
